### ISSUE TITLE
Create PyPI packages for nbsetuptools

### ISSUE THREAD

**Issue by ijstokes** [Anaconda-Server/anaconda-nb-extensions#104]
For `nbpresent` to be switched over to use `nbsetuptools` will mean creating PyPI packages for `nbsetuptools` and `nbwrapper`.  So we need to do that.

* [x] `nbsetuptools` PyPI
* ~~[ ] `nbwrapper` PyPI~~

We also need to document the process for uploading new packages there as required.

**Comment by damianavila** [comment]
We probably need to make pypi packages for all of our public extensions... or do we want to keep it as conda things to "force" people to use conda?

**Comment by ijstokes** [comment]
We do not need to force people to use conda, so pypi packages will make sense when we've got time to do this and when the packages are ready for public consumption.

I think the decision we came to is that until the Jupyter PR to support extensions installed in multiple locations is addressed this is lower priority.

**Comment by damianavila** [comment]
>I think the decision we came to is that until the Jupyter PR to support extensions installed in multiple locations is addressed this is lower priority.

I agree...

**Comment by malev** [comment]
@damianavila @ijstokes are we reallyl creating a piypi package for `nbwrapper`? I though we killed that package

**Comment by damianavila** [comment]
>@damianavila @ijstokes @mmarchetti are we reallyl creating a piypi package for nbwrapper? I though we killed that package

No, this issue got stale on that aspect, nbwrapper is killed so we are not going to publish it on pypi...

**Comment by mmarchetti** [comment]
That's correct. So now, if we (for example) make nbpresent depend on nbsetuptools, how will non-conda users install and run it? Can they be successful with only nbsetuptools (and perhaps setting Jupyter environment variables), or do we need to create a pypi package of nb_config_manager?

**Comment by damianavila** [comment]
3 options:

1- We make a conda package to install in the user space (IIRC nbsetuptools allow to install in the user space if you don't pass a `prefix` in the activation step...

2- We tell people to use the environment variable

3- We make nb_config_manager available at pypi


I guess the cleanest solution should be the 3rd one... but open to other's suggestion...

**Comment by mmarchetti** [comment]
I like option 3, assuming nb_config_manager "just works" for that use case without more coding work. Otherwise, option 2. (I don't like option 1, because would create more configurations for us to test and support).

**Comment by stephenakearns** [comment]
Hi @damianavila and @mmarchetti  - where did we land on this one? This seems like a nice-to-have at this point (would prefer to make sure we've got testing coverage across our supported platforms first)

**Comment by stephenakearns** [comment]
Discussed with @damianavila  - contingent upon whether or not nbPresent wants to use nbSetupTools. Closing for now, but @bollwyvl can you reopen this you decide that this would be valuable (probably a short discussion with @ijstokes )

**Comment by bollwyvl** [comment]
I just tried this out: it's already pulling in notebook 4.1.0 for which there aren't a lot of other things available (widgets, etc) so it's hard to test, etc.

Perhaps we wait until 4.1.0 lands (and we have packages built) and we revist. But then yes, it would be good to also have it on PyPi. We could do also some outreach to other folk (bqplot, etc).

Also, on the branch that @mmarchetti did: it also request nbwrapper in meta.yml... is that still a thing?

**Comment by mmarchetti** [comment]
Nick,

nbwrapper is no longer needed - any reference to it should be removed. Most of our extensions now depend on nb_config_manager so configs will load from the conda environment.

Mike

Michael Marchetti
Software Engineer





585-703-0926 | cell
mmarchetti@continuum.io
www.continuum.io
