### ISSUE TITLE
Manual test of all extensions on all platforms with all Python versions

### ISSUE THREAD

**Issue by ijstokes** [Anaconda-Server/anaconda-nb-extensions#109]
**NOTE:** this should only be done after #110 is completed.

All extensions need install and run successfully as individual units on all platforms and all Python versions via a simple sequence of:

```
conda create -n nb_NAME -c anaconda-notebook nb_NAME
source activate nb_NAME
anaconda-notebook
```

It will be exciting once this can be done in an automated way, but right now I think we need to do this for 3 Python versions (2.6, 3.4, 3.5), 3 platforms (win, linux, osx), and all extension packages:

* [ ] ~~`nbwrapper`~~
* [x] `nb_helloworld`
* [x] `nb_locker`
* [x] `nb_revisioncontrol`
* [x] `nb_conda`
* [x] `nb_conda_kernels`
* [x] `anaconda-nb-extensions`
* [x] `nb-config-manager`

* [x] Linux 64
* [ ] Linux 32
* [x] Win 64
* [ ] Win 32
* [x] Mac
This needs to be done 100% from packages served by Anaconda Cloud in the `anaconda-notebook` channel.

**Comment by damianavila** [comment]
We should make another round test on available systems after building and uploading the latest changes in the packages...

**Comment by damianavila** [comment]
This should be considered as done some time ago. Let's close it and open a new one for testing if it is necessary...
