### ISSUE TITLE
Stretch: Get Automated Builds working for Windows

### ISSUE THREAD

**Issue by stephenakearns** [Anaconda-Server/anaconda-nb-extensions#111]
Get windows builds working for the extensions

- [ ] configuration problem: workers timeout waiting for response that never is coming (see flow)
- [ ] anaconda-server/anaconda-build#150 - all the Win-64+Python2.7 builds fail - permissions 
- [ ] we may be missing build dependencies (sizing applies to this line item)

**Comment by damianavila** [comment]
@stephenakearns do you know the status of this one? I mean the resolution steps on the build system side...

**Comment by bollwyvl** [comment]
I am presently working this for nbpresent. As it uses much of the same machinery as other things that have the whole enchilada of casperjs testing, it should be informative.

Shame on me for writing only bash scripts for my tasks! I'll either have to rewrite them in node or in python, I suppose... leaning towards python!

**Comment by bollwyvl** [comment]
Here's an error I am seeing:
```
http://anaconda.org/anaconda-nb-extensions/nbpresent/builds/4/9
8IOError: [Errno 13] Permission denied: u'C:\\Users\\binstar\\Miniconda\\pkgs\\markupsafe-0.23-py27_0\\Lib\\site-packages\\markupsafe\\_speedups.pyd'

1039Exit BINSTAR_BUILD_RESULT=failure
```

I'm trying to reproduce it locally, or figure out which package is causing that particular chain of events to. Whee!

**Comment by damianavila** [comment]
Just to keep a record of this... currently there seems to be some issue with all the win workers which makes the win builds fail... for instance: https://anaconda.org/anaconda-nb-extensions/nb_locker/builds/7

**Comment by stephenakearns** [comment]
known remaining issues: 
- no Win32 support
- no Linux32+Py27 support

closing this for the timebeing until someone raises it again.
