### ISSUE TITLE
Review existing notebook diff options

### ISSUE THREAD

**Issue by ijstokes** [Anaconda-Server/anaconda-nb-extensions#113]
@damianavila reports that there is work underway to do a notebook diff.  Need to evaluate it and figure out how we can incorporate it into the Anaconda Platform.

https://github.com/martinal/nbdime

**Comment by damianavila** [comment]
And the enhancement proposal here: https://github.com/jupyter/enhancement-proposals/pull/8

**Comment by martinal** [comment]
Be warned that this is still in the prototyping stage! What kind of use cases does "incorporate it into the Anaconda Platform" include?

**Comment by damianavila** [comment]
Hey @martinal!
We know it is in prototype stage... but it makes sense to us to take a look on what others have been working on and if we can build thing on top of that or directly contribute to that effort... but, in fact, I still have to read throughout the source nbdime code :wink: so expect some question from me in the future :stuck_out_tongue_winking_eye:

**Comment by martinal** [comment]
Ok, great. I just pushed fixes that make nbmerge work for at least the one nontrivial testcase I used. A lot of the further work will be to find corner cases that do not work well.
