### ISSUE TITLE
Login to anaconda-client from the notebook

### ISSUE THREAD

**Issue by malev** [Anaconda-Server/anaconda-nb-extensions#115]
In order to login though the notebook, jupyter will need to send the credentials to the server. Since it does not have an ssl connection we need to find a secure way to do this.
Consider: http://stackoverflow.com/questions/13471115/how-to-handle-a-request-with-https-protocol-in-tornado

**Comment by damianavila** [comment]
This was done here: https://github.com/Anaconda-Server/nb_anacondacloud/pull/13
Closing.
