### ISSUE TITLE
Migrate theme to a new repo/conda package.

### ISSUE THREAD

**Issue by damianavila** [Anaconda-Server/anaconda-nb-extensions#122]
So people can disable it if they want just removing the package.

**Comment by stephenakearns** [comment]
@damianavila and @malev - did this happen or is it still waiting to be completed?

**Comment by damianavila** [comment]
I wrote two PRs for this one:

* https://github.com/Anaconda-Server/anaconda-nb-extensions/pull/124
* https://github.com/Anaconda-Server/nb_anaconda_theme/pull/1

Should be reviewed before merging those ones...

**Comment by damianavila** [comment]
I wrote two PRs for this one:

* https://github.com/Anaconda-Server/anaconda-nb-extensions/pull/124
* https://github.com/Anaconda-Server/nb_anaconda_theme/pull/1

Should be reviewed before merging those ones...

**Comment by damianavila** [comment]
PRs merged. Closing.
