### ISSUE TITLE
Work to migrate to a new org, clean the aCloud space, fix some issues and test the extensions

### ISSUE THREAD

**Issue by damianavila** [Anaconda-Server/anaconda-nb-extensions#129]
* [x] Created a new org: https://anaconda.org/anaconda-nb-extensions
* [x] Setup the organization to be Unlimited Free
* [x] Use the CIO queue (upstream work)
* [x] Enable webhooks for building of all the extensions
* [x] Update all the repo poiting to the new org, sync all the `.binstar` files and bump versions
* [x] Migrate all the remaining auxiliary packages: ~~traitlets~~, pandoc, gmp, ~~jsonpointer~~
* ~~[ ] Build all the packages locally until the build upstream win system is fixed (or alternative use the build system knowing that we miss win-py27 for now)~~
* ~~[ ] Test all the packages (on linux at first)~~
* ~~[ ] Test all packages on MacOS~~
* ~~[ ] Test all packages on Win64 and Win32~~
* [x] Upload "release" packages (manually) after merging PRs

PRs addresing these points:

* [x] https://github.com/Anaconda-Server/anaconda-nb-extensions/pull/127
* [x] https://github.com/Anaconda-Server/nb_config_manager/pull/6
* [x] https://github.com/Anaconda-Server/nb_conda_kernels/pull/3
* [x] https://github.com/Anaconda-Server/nb_anaconda_theme/pull/2
* [x] https://github.com/Anaconda-Server/nb_conda/pull/6
* [x] https://github.com/Anaconda-Server/nbsetuptools/pull/6
* [x] https://github.com/Anaconda-Server/nb_helloworld/pull/7
* [x] https://github.com/Anaconda-Server/generator-nbextension/pull/3
* [x] https://github.com/Anaconda-Server/nb_locker/pull/7 ~~(local branch, need Unlimited account to make it private)~~
* [x] https://github.com/Anaconda-Server/nb_revisioncontrol/pull/4 ~~(local branch, need Unlimited account to make it private)~~
* [x] https://github.com/Anaconda-Server/nb_anacondacloud (need to merge some PRs before the update)
  - integration tests
    - issue https://github.com/Anaconda-Server/anaconda-nb-extensions/issues/128
    - PR https://github.com/Anaconda-Server/nb_anacondacloud/pull/8
  - UI rework
    - PR https://github.com/Anaconda-Server/nb_anacondacloud/pull/6
* [x] https://github.com/Anaconda-Server/nbpresent (need to migrate webhook to the new org, also check compat with nb_config_manager)
* [x] https://github.com/Anaconda-Server/nbbrowserpdf (need to migrate webhook to the new org, also check compat with nb_config_manager)

**Comment by damianavila** [comment]
@stephenakearns this is a list of the things I have done yesterday and today... I did not want to lose track of the work done... also this will be you work with the visibility thing you mention today at the standup (if you need to split this further, we can do that too, but it was easy to just mention all the things in this issue).
I will try fill the holes until Monday when I shift to wakari work (or I will try to complete them in the little holes I can find in the other task),

**Comment by bollwyvl** [comment]
On nbbrowserpdf and nbpresent: just to clarify, nb_config_manager will work with pypi downloads, as well? If not, I am not entirely against being conda only, but I think it would hurt adoption throughout the broader community.

**Comment by damianavila** [comment]
> On nbbrowserpdf and nbpresent

Any change in those should not affect how the extension are currently installed and loaded. I don't pretend to make them conda-only :wink:

**Comment by damianavila** [comment]
Just to update @stephenakearns, making some progress on this today merging a lot of PR and building packages... in the middle I have found some issues in the Anaconda Build system I have already posted in the proper flow...

**Comment by damianavila** [comment]
Another PR: https://github.com/Anaconda-Server/nb_helloworld/pull/8

**Comment by damianavila** [comment]
Some others PRs:

* https://github.com/Anaconda-Server/nb_conda_kernels/pull/5 (Rkernel detection)
* https://github.com/Anaconda-Server/nb_conda/pull/7
* https://github.com/Anaconda-Server/nb_locker/pull/8
* https://github.com/Anaconda-Server/nb_revisioncontrol/pull/8
* https://github.com/Anaconda-Server/nb_revisioncontrol/pull/9

**Comment by damianavila** [comment]
Two more:

* https://github.com/Anaconda-Server/nbpresent/pull/38
* https://github.com/Anaconda-Server/nbbrowserpdf/pull/9

**Comment by stephenakearns** [comment]
Hi @damianavila  - checking in on this one - latest PRs are merged. I see the last remaining checkbox (manual upload) - LMK if there's anything blocking closing this item?

**Comment by stephenakearns** [comment]
update from @damianavila:
Today:
finish the review of the uptream PR.
merge some fixes from Nick related with win builds
try to finally build the metapackage for the extensions (now that I have nbbrowserpdf available for some platforms)

**Comment by damianavila** [comment]
Manual upload is done for all the packages... still some missing pieces in win packages for nbpresent, but let's defer that for other issue and make an new one for the metapackage, not covered here...

**Comment by damianavila** [comment]
For reference:

>finish the review of the uptream PR.

waiting for PR updates...

>merge some fixes from Nick related with win builds

I did it yesterday...

>try to finally build the metapackage for the extensions (now that I have nbbrowserpdf available for some platforms)

open #140 to discuss this one...
