### ISSUE TITLE
Update nb-extensions when Jupyter Notebook 4.2 released

### ISSUE THREAD

**Issue by stephenakearns** [Anaconda-Server/anaconda-nb-extensions#130]
approximate release date - Mid-Feb

* [ ] jupyter notebooks - finish discussion and merge PR (2) #138
* [ ] port existing extensions - one PR against each extension (3) #139
* [ ] test against release candidate when it becomes available cross platform (2)
* [ ] final smoke test against the final released version (1)

**Comment by damianavila** [comment]
Closing this one because we opened issues for each task, so we don't size twice...

**Comment by stephenakearns** [comment]
removed sizing b/c the sizing will be located in each of the break-out issues
