### ISSUE TITLE
[nbpresent] Discuss integration of nbPresent into Anaconda Repo/Cloud

### ISSUE THREAD

**Issue by stephenakearns** [Anaconda-Server/anaconda-nb-extensions#131]
* [ ] heavy dependencies: PyQT, PyPDF
* [ ] long-running, async job (reuse approach with nbConvert?)
* [ ] upgrade to nbConvert 4.2 to gain benefits?
* [ ] Key output: design/approach 

Consumer End User Experience:
- 1st scenario: hacker news: link to notebook on notebooks.anaconda.org and URL is specific to presentation mode
- 2nd scenario: link to notebooks, but doesn't have nbpresent URL specifier >> you see regular UI and there's a button on page 

![image](https://cloud.githubusercontent.com/assets/13372164/12583915/a481b640-c40a-11e5-97c0-cbf65e7cb509.png)

**Comment by bollwyvl** [comment]
The UI for notebooks changed a bunch with the v2.14.2 release.

Here's what would have to happen:
- [ ] get acquainted with the new code
- [ ] do a design mockup
  - [ ] re-expose version
  - [ ] re-expose download on view page
  - [ ] add multiple output formats
- [ ] consider making notebook rendering an async task (if not already)
- [ ] figure out an approach for a second host/port for served notebooks
  - [ ] second host:port to prevent js issues
  - [ ] some amount of auth to keep notebooks private
  - [ ] start second port with `honcho`
- [ ] decide on the URL scheme for
  - [ ] the branded UI "wrapper"
    - e.g. `https://anaconda.org/nbcio/untitled/notebook?format=nbpresent`
  - [ ] the iframe
    - e.g. `https://anaconda.org:8888/nbcio/untitled/notebook?format=nbpresent`

**Comment by bollwyvl** [comment]
We discussed this!
Issue: https://github.com/Anaconda-Server/anaconda-server/issues/1573
PR: https://github.com/Anaconda-Server/anaconda-server/pull/1583
