### ISSUE TITLE
[nbpresent] windows build on anaconda.org

### ISSUE THREAD

**Issue by bollwyvl** [Anaconda-Server/anaconda-nb-extensions#135]
Instead of holding up #39, let's concentrate on the windows build here.

- [ ] get building locally:
  - [x] convert bash scripts to python (70%)
- [ ] find all the right channels for packages
  - [ ] maybe build some packages
- [ ] inevitably debug differences between local windows vmware fusion box and anaconda cloud

**Comment by bollwyvl** [comment]
So presently waiting for `conda build` to run on windows. Whew, these are going to take a while!

All of the build tasks are now in python, so should be cross-platform for the foreseeable. The next iteration may indeed to be to go to grunt, but I'm happy with where I am now.

I should have a PR up soon, and we can burn some coal to see how I'm doing :)

**Comment by bollwyvl** [comment]
Still having issues on linux-32 and win-64:
http://anaconda.org/anaconda-nb-extensions/nbpresent/builds/17/2#L183
http://anaconda.org/anaconda-nb-extensions/nbpresent/builds/17/11#L2409

It's possible both of these would be fixed with an up-to-date node, though on win it looks like bld.bat is not being run in its entirety.

**Comment by stephenakearns** [comment]
Related to Anaconda-Server/nb_conda#9

**Comment by stephenakearns** [comment]
Build issue: with markupsafe not working on Windows 32 builds, not able to support platform.

**Comment by ijstokes** [comment]
@bollwyvl what are the implications of this? Does it mean nbpresent can't be run on Windows?  If so, are there any alternatives for how to resolve that obstacle?

**Comment by bollwyvl** [comment]
@ijstokes We aren't running win-32/py27 builds on much of anything, as the notebook and conda share dependencies, and therefore cannot by cleaned (apparently) as part of the build.

We have our packaging script which will do the convert so we can release on that platform, but it means we have no confidence in our XP coverage, something which nobody is interested in pursuing locally.

**Comment by bollwyvl** [comment]
Well, this builds on windows-64, on the different pythons, so I'm happy to call it closed. Again I see the win32 support story as something we address once there is a need.
