### ISSUE TITLE
Theming for static export (nbpresent HTML, PDF)

### ISSUE THREAD

**Issue by stephenakearns** [Anaconda-Server/anaconda-nb-extensions#137]
related to Anaconda-Server/nbpresent#34

remaining work: 
* [x] font
* [x] font size
* [x] background image
* [x] build "canned" themes (light, dark, Anaconda)
* [x] documentation
  * [x] inline help in notebook 
  * [x] basic readme content on repo (can point to in-line help for detailed info
  * [x] tour (needs updates)
* [x] integration tests passing
* [x] manual builds of conda packages for: Mac (for us to test) and Win64 for the rest of the Continuum world (Linux-64 is bonus)
* [ ] team functional testing (2 people - @malev and @damianavila and @stephenakearns )
* [ ] UAT ( @ijstokes or @chdoig ) - provide link to docs - and then full-self-serve from there to successful publishing presentation on A-Cloud
* [x] communication/documentation/support plan? 

### Stretch Goals
* [ ] docs.nbpresent.io (or some kind of equivalent)
* [ ] end-user tutorials
* [ ] response for end-user requests for customizations
* [ ] offline fonts (conda install package) (WIP)
* [ ] Automated build packages
* [ ] A-Cloud watermark 
* [ ] test in Anaconda Enterprise Notebooks (Wakari Enterprise)
* [ ] demo friday

**Comment by stephenakearns** [comment]
Question: knowing that we are going thru updated branding activities which will drive changes to look and feel across a lot of continuum real estate & HTML :
- all CSS is in LESS/SCSS/Stylus
- LESS used by Jupyter
- Phosphor using Stylus (akin to YAML)
- Anaconda Server uses 
- noteworthy: https://github.com/7sempra/rosetta (sharing vars btw. CSS & Javascript
- Background - 50 min talk on Atomic Design and Sketch (OSS for OSX) - https://medium.com/re-write/the-unicorn-workflow-design-to-code-with-atomic-design-principles-and-sketch-8b0fe7d05a37#.jrbdt39ca

@mistakevin @goanpeca @FirecatSue - thoughts?

**Comment by stephenakearns** [comment]
Adding Nick's technical details in from #134 

This work can be thought of as Themes 1.0. All config will be at the _whole presentation_ level, without precluding the later customization of individual slides and regions.

## Technical Challenges

> this might grow

- [ ] theme loading (new server route)
  - [ ] for the time being, define these as python (conda/pip) packages
  - [ ] distribute the fonts
- [x] data model for themes
- [ ] pick theme presets in web UI
  - [x] initial thought: "style guide" UI
- [x] actually update elements in presentation!
  - [x] make sure it turns off!
- [ ] off-line build with embedded fonts
- [ ] verify functionality with offline viewer (ghost.py CSS)
- [ ] build themes!
  - [x] `null`: doesn't do anything
  - [ ] `base:light`: extremely minimal, most of the opinions from notebook, except fonts (helvetica and arial, begone!)
  - [ ] `base:dark`: inverted from above (maybe the jupyter orange instead of the blue, etc). 
  - [ ] `anaconda:watermark`: adds the _powered by anaconda_ watermark to a corner slot
  - [ ] `continuum:corp`: the continuum presentation template. lots to do.

**Comment by damianavila** [comment]
@stephenakearns @bollwyvl closing this because I believed is done. Futher themes discussion should probably follow-up in a new issue.
