### ISSUE TITLE
Contribute to completion of Jupyter Notebook PR #879

### ISSUE THREAD

**Issue by ijstokes** [Anaconda-Server/anaconda-nb-extensions#138]
Based on a preview of our work Brian Granger initiated a discussion about how to do this in a common way that would work for Jupyter 4.x and possibly into 5.x, depending on how the extension mechanism ports over.

That conversation started [JEP-7 (by NickB)](https://github.com/jupyter/enhancement-proposals/pull/7), but then Brian took the conversation [HERE (Issue #878)](https://github.com/jupyter/notebook/issues/878), where the work then happened on [PR #879](https://github.com/jupyter/notebook/issues/879).

The conversation about this process happened in Flowdock and is captured below:

**Ian:**
@NickB, and @Damian: I emailed Brian Granger yesterday about the NB extension configuration work for Jupyter 4.2 (PR #879) to explicitly ask what we can do to help move things forward to wrap up this PR.  Please can you let me know what your best understanding is of what we need to do to help, and what the timeline is for the PR and for Jupyter 4.2.  I also need to understand what the impact is on us:
* what will happen if (hypothetically) 4.2 is delayed for another 2 months;
* what we'll gain when 4.2 comes out with the new extension configuration;
* what work we'll need to do once the PR is finalized and merged to adapt our extensions to account for this.

**NickB**
what will happen if (hypothetically) 4.2 is delayed for another 2 months
nothing, to us. our mechanism is sound

**Damian**
@Ian, as @NickB said, the meeting was aranged in the jupyter mailing list... I did not ping you about it because you were working in the trial VM and the discussion on the new nbextension load mechanism was almost done (it needed just some last details we discussed in the meeting... you can see the meeting minutes to check more about that (it was also recorded if you are interested into hear what we discuss...

**NickB**
what we'll gain when 4.2 comes out with the new extension configuration;
all extension authors will be able to write less code, and their users will have a less bewildering experience when installing notebook extensions
we will be able to get rid of some duplicate code, and potentially deprecate some code
what work we'll need to do once the PR is finalized and merged to adapt our extensions to account for this.
damian would have a better handle on this, but i think we'll either just get to take code out, or remove dependencies
i defer to damian on all these things
💵 passed :)

**Ian**
@Damian and Thanks guys. Turns out I am on that mailing list but had all email turned off.  Key questions:
* What do we have to do now (actions and approx time) to help bring this PR to completion?
* What is the expected timeline for the PR to be completed and merged?
* How much work do we expect we'll need to do on our extensions to work with this PR's extension config model once it is merged?
* What is the expected timeline for Jupyter 4.2 release?

**Damian**
@Ian, related with the three point you raised above:
* if the release is delayed we still can release with the present mechanism for 4.1 and switch to the official one later (but I hope 4.2 will be released sooner than later...
* when 4.2 is out, if we convert our extension to use the "canonical" mechanism, we no longer use our custom config manager... we use the notebook nbextension API to insttall ana enable the extension in prefix... and the notebook will load that config from prefix (not only from the user space)
* when the PR is merged, we need to convert our extension to the new mechanism, getting rid of nbsetuptools and nb_config_manager because the notebook nbextension API will provide the necessary thing to install AND enable the extension in prefix...

@Ian, in my task for this week is to help finish the PR and merge it so we can have a quick iteration to achieve 4.2...
I would say, this week for refinement and merge...
To make our extensions to work with the new mechanism we will need a week... I guess... we have to do a lot of changes but it should be easier once we have one done... I am starting to make one of our extension work with the PR...
And for the release... I guess maybe 2/3 weeks from now... although it can be more... depending on testing, rc and final release

**Comment by stephenakearns** [comment]
Hi @ijstokes and @damianavila - this issue looks like more of the discussion about Jupyter 4.2 and damian has opened #139 to track the work for this. Can we close this issue now? Closing, but please reopen if there's still more work to do on this one.

**Comment by damianavila** [comment]
I reopened this to track the work on this issue.
I have reviewed and make some porting experiments with nb_conda. I left some comments in the issue. We probably need to help finishing some missing pieces and tests.

**Comment by damianavila** [comment]
I have contribute with review, code, discussion... right now Jon is carry on the PR with others reviewing it. I guess this will be merged soon. This can be closed when the upstream PR is merged.

**Comment by damianavila** [comment]
879 was merged, we have notebook 4.2 beta out, so closing, BUT before... I updated the story points to something more accurate (although probably it is more than 8 story points... also, it is difficult to measure because it was an effort, mainly, by two people over a long period of time).
