### ISSUE TITLE
[nbpresent] Integrate into Anaconda Cloud

### ISSUE THREAD

**Issue by stephenakearns** [Anaconda-Server/anaconda-nb-extensions#143]
Tracking issue for actual issue here: 
Anaconda-Server/anaconda-server#1573

**Comment by damianavila** [comment]
https://github.com/Anaconda-Server/anaconda-server/issues/1573 was merged... so closing this one now!

**Comment by damianavila** [comment]
I reopened to change the estimate because I know that it was more than 5 (I followed the discussion on the PR).
