### ISSUE TITLE
Fix win paths and test calls in all the extensions

### ISSUE THREAD

**Issue by damianavila** [Anaconda-Server/anaconda-nb-extensions#144]
* We need to fix python path in several of our extensions
* We would like to use run_test.py for testing

So far PRs opened:

* [x] https://github.com/Anaconda-Server/nb_anaconda_theme/pull/3
* [x] https://github.com/Anaconda-Server/nb_conda/pull/11
* [x] https://github.com/Anaconda-Server/nb_conda_kernels/pull/10
* [x] https://github.com/Anaconda-Server/nb_config_manager/pull/10

Adding more as time permits...

**Comment by damianavila** [comment]
two more: 

* [ ] https://github.com/Anaconda-Server/nb_locker/pull/9
* [ ] https://github.com/Anaconda-Server/nb_revisioncontrol/pull/9

**Comment by bollwyvl** [comment]
also:
- [ ] https://github.com/Anaconda-Server/nb_anacondacloud/pull/9

**Comment by damianavila** [comment]
BTW, I am currently testing those in a new Win10 VM :unamused:

**Comment by damianavila** [comment]
and another one:
* [ ] https://github.com/Anaconda-Server/nbsetuptools/pull/7

**Comment by damianavila** [comment]
OK, all the PR are closed, so closing this one.
