### ISSUE TITLE
Create serverextension CLI mechanism

### ISSUE THREAD

**Issue by damianavila** [Anaconda-Server/anaconda-nb-extensions#147]
We need this to make nb_conda and other extension with server component to work OK.

**Comment by ijstokes** [comment]
@damianavila can you explain this a little more?  I think I understand what this means, but I'm not sure.  Is this something that would need to get pushed up stream?

**Comment by damianavila** [comment]
Yep, we need to push this upstream... with the current state in the upstream PR 879, the server component for our extension would need to still use a customize mechanism to be enable which put us again the the same position than before. This should be fixed in the notebook itself trhought a CLI mechanism such as the nbextensions mechanism proposed in the 879 PR.

I am prototyping the CLI, since we **can not** avoid this if we want our extension to run natively on the notebook, and it should be relatively easy to come up with a PR upstream on top of the 879 work.

**Comment by damianavila** [comment]
My contribution was merged in the main PR 879 here: https://github.com/ellisonbg/notebook/pull/1

So closing here for now.
