### ISSUE TITLE
HTML rendering from nbpresent slideshows (Linux64 and MacOS)

### ISSUE THREAD

**Issue by ijstokes** [Anaconda-Server/anaconda-nb-extensions#39]
Mechanism to create a static (kernel-free) HTML rendering of notebooks created with `nbpresent`

standard view:
* [x] CLI
* [x] in-notebook (GUI)

slideshow view:
* [ ] CLI
* [ ] in-notebook (GUI)

**Comment by damianavila** [comment]
@bollwyvl can you comment on this one again, if anything changed from your last comment...

**Comment by bollwyvl** [comment]
I haven't circled back to this one in a while. Really my best bet is to get the embedded javascript/css to actually _work_ a la bokeh rather than punting to using the zip file. I'll have a look presently: the roadblock I ran into involved some requirejs errors: perhaps I will need to go down the requirejs optimizer route for the standalone one.

also, i am shipping a number of things in the big dependency blob that may not be strictly necessary for the static build: as it is it will be pretty heavy.

**Comment by damianavila** [comment]
> Really my best bet is to get the embedded javascript/css to actually work a la bokeh rather than punting to using the zip file

Probably...

> also, i am shipping a number of things in the big dependency blob that may not be strictly necessary for the static build: as it is it will be pretty heavy.

Would be nice to just ship what is necessary...

Btw, thanks for your answer!

**Comment by bollwyvl** [comment]
Just tested the html output out with https://github.com/jupyter/nbconvert/pull/185, it's looking like we'll be ready to start using that once nbconvert [4.2](https://github.com/jupyter/nbconvert/milestones/4.2) ships, though in the meantime i'll keep shipping the `nbpresent` command line entrypoint.

now just to get the asset embedding working!

**Comment by bollwyvl** [comment]
Presently, this is working fine on linux-64 and osx.

Still stumbling on windows builds, trying to figure out some local issues, but there are probably also anaconda cloud issues:
https://github.com/Anaconda-Server/anaconda-nb-extensions/issues/111

**Comment by bollwyvl** [comment]
Changed to 3 points. Tracking windows build issues separately in #135. Waiting on build.

**Comment by bollwyvl** [comment]
Merged, waiting for build against master:

http://anaconda.org/anaconda-nb-extensions/nbpresent/builds/7

Provided that merges cleanly, i'll cut a 0.5.0 release, thought that may be this evening... snow day :snowman:!

**Comment by bollwyvl** [comment]
Builds are up:
http://anaconda.org/anaconda-nb-extensions/nbpresent/files?version=0.5.0
