### ISSUE TITLE
Publish notebooks to Anaconda Repository (Enterprise/Cloud)

### ISSUE THREAD

**Issue by mmarchetti** [Anaconda-Server/anaconda-nb-extensions#47]
Idea: Notebook-centric operations related to Notebook publishing/sharing on Anaconda
- [ ] publish (anaconda upload) - should include link back to location on A-Cloud (minimal - no switches)
- [ ] ~~version (not sure this is currently possible)~~
- [ ] ~~meta-data (defer: not sure exactly what this would mean, or what Anaconda Server would support)~~
- [ ] ~~dependencies (could defer: this is capturing environment or specific package requirements and somehow associating or embedding in notebook meta-data)~~
- [ ] ~~ACL (who can read this published notebook?) -- This requires some careful thought since ACLs are at the “abstract” notebook level (all notebook versions within a particular channel/name pair), and are stored on the server. At a minimum, ability to set “public” or “private” (in fact, “force” this setting for all notebook versions). More advanced will need to poll server to find out current settings and sensibly present options.~~

[extracted from epic #32]

## Reduced Scope Specification

See visual references for aspects of this work in #22 

* [ ] Login (`anaconda login`), available under *File* menu (or *Anaconda* menu if that ever appears)
* [ ] Publish (`anaconda upload --private MyFancyNotebook.ipynb`), available under *File* menu

Both should provide some visual queues in the status bar (no pop-up overlay dialogs!) as to the result of these operations.  If `--private` doesn't exist (yet) in `anaconda upload` then fine, indicate that the uploaded notebook is public somehow.  And, of course, provide the URL to the notebook.

**Comment by stephenakearns** [comment]
@bollwyvl to test out - lives in the anaconda-server/nb_anacondacloud repo. 

first thing to try: `conda install -c anaconda-notebook anaconda-nb-anacondacloud`

- upload notebook or package directly to your account in anaconda cloud
- should present a link to the spot on A-cloud

**Comment by damianavila** [comment]
AFAIK, this is covered by #50, so there is some duplication... in any case, @bollwyvl has reviewed, tested and proposed PRs to nb_anaconda_cloud, so he probably can give more details but I guess we can close this one as done 
ping @malev and @stephenakearns as well...

**Comment by damianavila** [comment]
@stephenakearns I will close this one, reopen it if you believe is not the case to close it.
