### ISSUE TITLE
PR on Jupyter for configuration fetched from environment

### ISSUE THREAD

**Issue by ijstokes** [Anaconda-Server/anaconda-nb-extensions#70]
* Edited by Damian 4 Dic 11:05 am ARG time

Currently, in Jupyter, nbconfig is only fetched in two ways: from `~/.jupyter/ or from the directory pointed to by the environment variable `JUPYTER_CONFIG_DIR`.  This makes it awkward (in fact, almost impossible) for Jupyter to be launched in a way that fetches configuration from a conda (or for that matter virtualenv) sandbox unless you specified the condif dir...

This is despite the fact that Jupyter knows there are more places where configuration information *may* exist:

```bash
$ jupyter --paths
config:
    /Users/ijstokes/.jupyter
    /Users/ijstokes/anaconda/envs/j/etc/jupyter
    /usr/local/etc/jupyter
    /etc/jupyter
data:
    /Users/ijstokes/Library/Jupyter
    /Users/ijstokes/anaconda/envs/j/share/jupyter
    /usr/local/share/jupyter
    /usr/share/jupyter
runtime:
    /Users/ijstokes/Library/Jupyter/runtime
```

This is a known issue and is currently scheduled to be addressed in Jupyter 5.x (early), but we may need it sooner than that, and we may need or want to be the ones who make this happen.

Additionally, because of our desire to have conda-installable extensions (meaning: automated), we probably want to have the idea of a `conf.d` directory where individual configuration fragments can be dropped, rather than having to do complicated modifications in a single config file.

**Comment by ijstokes** [comment]
Further to the extensive discussion here: https://github.com/jupyter/enhancement-proposals/pull/7

We agreed that @damianavila would investigate just how much work he thought would be required to modify Jupyter to support the scenario we're describing here.  So we're waiting for that feedback to confirm the sizing estimate to establish if we'll proceed with the task to address this story or if we'll defer.

**Comment by ijstokes** [comment]
Some of this has been covered in Jupyter Notebook PR https://github.com/jupyter/notebook/pull/882 (by @damianavila) which has already been merged (yay!)

**Comment by damianavila** [comment]
Work to be done:

* [ ] Complete my EnvironmentConfigManager implementation, make it a package and put it in a new repo
* [ ] Remove the nbwrapper
* [ ] Make all our extensions to depend on the new `EnvironmentConfigManager`

**Comment by damianavila** [comment]
The last three points should probably be moved to the next sprint... in fact, this three rows are new work that emerged by the discussion with the rest of Jupyter team and as an alternative to the current status quo dealing with extensions installed outside the user space.

The discussion and the fix upstream (in the notebook) exceeded the estimated points for this card. 

@stephenakearns what do you think about closing this one as done with the fix upstream and port the remaining steps (three point described above) for the next sprint? Or how do you think we have to manage this one?
