### ISSUE TITLE
anaconda-notebook blog post

### ISSUE THREAD

**Issue by ijstokes** [Anaconda-Server/anaconda-nb-extensions#98]
A blog post to cover all the awesome stuff we've created in this epic, starting with `condaenvs` extension and including also (ideally) some third-party extensions that we've ported into our extension format (to work with conda), and references to the `nbpresent` blog post and a "building Jupyter extensions" blog post.

**Comment by damianavila** [comment]
#97 and #99 cover this, so closing here.
